package com.siestech.booksharing.Practical;

import android.Manifest; import android.bluetooth.BluetoothAdapter; import android.bluetooth.BluetoothDevice; import android.content.BroadcastReceiver; import android.content.Context; import android.content.Intent; import android.content.IntentFilter; import android.content.pm.PackageManager; import android.os.Build; import android.os.Bundle; import android.widget.ArrayAdapter; import android.widget.Button; import android.widget.ListView; import android.widget.TextView; import android.widget.Toast; import androidx.annotation.NonNull; import androidx.appcompat.app.AppCompatActivity; import androidx.core.app.ActivityCompat; import com.siestech.booksharing.R; import java.util.ArrayList; import java.util.Set;

public class BluetoothShareActivity extends AppCompatActivity {
 private BluetoothAdapter adapter; private final ArrayList<String> devices=new ArrayList<>(); private ArrayAdapter<String> listAdapter; private static final int BT=92; private String shareText="BorrowBox book";
 private final BroadcastReceiver receiver=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){if(BluetoothDevice.ACTION_FOUND.equals(i.getAction())){BluetoothDevice d=i.getParcelableExtra(BluetoothDevice.EXTRA_DEVICE);if(d!=null){String s=safeDeviceName(d)+"\n"+d.getAddress();if(!devices.contains(s)) {devices.add(s);listAdapter.notifyDataSetChanged();}}}}};
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_bluetooth);shareText=getIntent().getStringExtra("shareText");if(shareText==null)shareText="BorrowBox — book sharing";TextView status=findViewById(R.id.btStatus);ListView list=findViewById(R.id.devicesList);listAdapter=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,devices);list.setAdapter(listAdapter);adapter=BluetoothAdapter.getDefaultAdapter();if(adapter==null){status.setText("Bluetooth not supported");return;}updateStatus(status);findViewById(R.id.enableBtBtn).setOnClickListener(v->{if(!hasConnectPermission()){requestBt();return;}try{if(!adapter.isEnabled())startActivityForResult(new Intent(BluetoothAdapter.ACTION_REQUEST_ENABLE),10);}catch(SecurityException ignored){}});findViewById(R.id.discoverableBtn).setOnClickListener(v->{if(!hasConnectPermission()){requestBt();return;}Intent i=new Intent(BluetoothAdapter.ACTION_REQUEST_DISCOVERABLE);i.putExtra(BluetoothAdapter.EXTRA_DISCOVERABLE_DURATION,300);startActivity(i);});findViewById(R.id.discoverBtn).setOnClickListener(v->discover());list.setOnItemClickListener((p,v,pos,id)->shareOverBluetooth());registerReceiver(receiver,new IntentFilter(BluetoothDevice.ACTION_FOUND));showPaired();}
 private boolean hasConnectPermission(){return Build.VERSION.SDK_INT<31||ActivityCompat.checkSelfPermission(this,Manifest.permission.BLUETOOTH_CONNECT)==PackageManager.PERMISSION_GRANTED;}
 private void requestBt(){if(Build.VERSION.SDK_INT>=31)ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.BLUETOOTH_CONNECT,Manifest.permission.BLUETOOTH_SCAN},BT);}
 private void discover(){if(!hasConnectPermission()){requestBt();return;}devices.clear();showPaired();try{adapter.cancelDiscovery();adapter.startDiscovery();Toast.makeText(this,"Discovery started",Toast.LENGTH_SHORT).show();}catch(SecurityException e){Toast.makeText(this,"Bluetooth permission required",Toast.LENGTH_SHORT).show();}}
 private void showPaired(){if(adapter==null||!hasConnectPermission())return;try{Set<BluetoothDevice> set=adapter.getBondedDevices();for(BluetoothDevice d:set){String s=safeDeviceName(d)+"\n"+d.getAddress();if(!devices.contains(s))devices.add(s);}if(listAdapter!=null)listAdapter.notifyDataSetChanged();}catch(SecurityException ignored){}}
 private String safeDeviceName(BluetoothDevice d){try{String n=d.getName();return n==null?"Unnamed device":n;}catch(SecurityException e){return "Bluetooth device";}}
 private void updateStatus(TextView v){try{v.setText(adapter.isEnabled()?"Bluetooth is ON":"Bluetooth is OFF");}catch(SecurityException e){v.setText("Bluetooth permission required");}}
 private void shareOverBluetooth(){Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,shareText);i.setPackage("com.android.bluetooth");try{startActivity(Intent.createChooser(i,"Share via Bluetooth"));}catch(Exception e){i.setPackage(null);startActivity(Intent.createChooser(i,"Choose sharing app"));}}
 @Override protected void onDestroy(){try{unregisterReceiver(receiver);}catch(Exception ignored){}try{adapter.cancelDiscovery();}catch(Exception ignored){}super.onDestroy();}
 @Override public void onRequestPermissionsResult(int r,@NonNull String[] p,@NonNull int[] g){super.onRequestPermissionsResult(r,p,g);if(r==BT)Toast.makeText(this,"Bluetooth permission updated",Toast.LENGTH_SHORT).show();}
}
