package com.siestech.booksharing.Practical;
import android.content.*; import android.database.Cursor; import android.database.sqlite.*; import android.os.Bundle; import android.widget.*; import androidx.appcompat.app.AppCompatActivity; import com.siestech.booksharing.R; import java.util.*;
public class SQLiteLibraryActivity extends AppCompatActivity{
 private DB db; private EditText title,author,search; private ListView list; private ArrayAdapter<String> adapter; private ArrayList<String> labels=new ArrayList<>(); private ArrayList<Integer> ids=new ArrayList<>(); private int selected=-1;
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_sqlite);db=new DB(this);title=findViewById(R.id.localTitle);author=findViewById(R.id.localAuthor);search=findViewById(R.id.localSearch);list=findViewById(R.id.localList);adapter=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,labels);list.setAdapter(adapter);findViewById(R.id.insertBtn).setOnClickListener(v->insert());findViewById(R.id.updateBtn).setOnClickListener(v->update());findViewById(R.id.deleteBtn).setOnClickListener(v->delete());search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){load(s.toString());}public void afterTextChanged(android.text.Editable e){}});list.setOnItemClickListener((p,v,pos,id)->{selected=ids.get(pos);String[] parts=labels.get(pos).split(" — ",2);title.setText(parts[0]);author.setText(parts.length>1?parts[1]:"");});load("");}
 private void insert(){String t=title.getText().toString().trim(),a=author.getText().toString().trim();if(t.isEmpty()||a.isEmpty()){Toast.makeText(this,"Enter title and author",Toast.LENGTH_SHORT).show();return;}db.getWritableDatabase().execSQL("INSERT INTO books(title,author) VALUES(?,?)",new Object[]{t,a});Toast.makeText(this,"Inserted",Toast.LENGTH_SHORT).show();clear();load("");}
 private void update(){if(selected==-1){Toast.makeText(this,"Select a book first",Toast.LENGTH_SHORT).show();return;}db.getWritableDatabase().execSQL("UPDATE books SET title=?, author=? WHERE id=?",new Object[]{title.getText().toString().trim(),author.getText().toString().trim(),selected});Toast.makeText(this,"Updated",Toast.LENGTH_SHORT).show();load("");}
 private void delete(){if(selected==-1){Toast.makeText(this,"Select a book first",Toast.LENGTH_SHORT).show();return;}db.getWritableDatabase().delete("books","id=?",new String[]{String.valueOf(selected)});Toast.makeText(this,"Deleted",Toast.LENGTH_SHORT).show();selected=-1;clear();load("");}
 private void clear(){title.setText("");author.setText("");}
 private void load(String q){labels.clear();ids.clear();Cursor c=db.getReadableDatabase().rawQuery("SELECT id,title,author FROM books WHERE title LIKE ? OR author LIKE ? ORDER BY id DESC",new String[]{"%"+q+"%","%"+q+"%"});while(c.moveToNext()){ids.add(c.getInt(0));labels.add(c.getString(1)+" — "+c.getString(2));}c.close();adapter.notifyDataSetChanged();}
 static class DB extends SQLiteOpenHelper{DB(Context c){super(c,"BorrowBoxLocal.db",null,1);}public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE books(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,author TEXT NOT NULL)");}public void onUpgrade(SQLiteDatabase d,int a,int b){d.execSQL("DROP TABLE IF EXISTS books");onCreate(d);}}
}
